---
# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see:
# https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]

    steps:
    # Clone code to workspace
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip poetry
        poetry install --no-interaction
    - name: Lint & Code Format
      run: |
        echo 'Running Flake8' && \
        poetry run flake8 . && \
        echo 'Running Black' && \
        poetry run black --check --diff . && \
        echo 'Running Yamllint' && \
        poetry run yamllint . && \
        echo 'Running pydocstyle' && \
        poetry run pydocstyle . && \
        echo 'Running Bandit' && \
        poetry run bandit --recursive ./ --configfile .bandit.yml
    - name: Test with pytest
      run: |
        poetry run pytest --cov=nornir_pyxl --color=yes -vvv
